Create Задание 2-1.c
VelichkoIS/TKI-142 pull request #12
Opened 2024-10-27 22:08 UTC by VelichkoIS

Выполнил 2-1

2024-10-28 11:31 UTC, MarinaPaley requested changes

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +double trapezoidcalculation(double a, double b, double h);
const

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +double circlecalculation(double r);
const

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +double input(ShapeType shape);
const

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +    printf("Выберите фигуру для расчета площади:\n1 - Трапеция\n2 - Круг\nВаш выбор: ");
константы в коде

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +    }
В отдельную функцию

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +    return 0;
через switch case

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +        double a, b, h;
Зачем?

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +        }
В отдельную функцию

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +        }
то же

2024-10-28 11:31 UTC, MarinaPaley commented on Задание 2-1.c
> +double input(ShapeType shape) {
Убрать эту функцию. содержимое в main

2024-12-11 13:50 UTC, MarinaPaley requested changes

2024-12-11 13:50 UTC, MarinaPaley commented on Задание 2-1.c
> +* @var s - переменная для хранения количества символов введенных в stdin
Докусентация выполнена неправльно

2024-12-11 13:50 UTC, MarinaPaley commented on Задание 2-1.c
> +double trapezoidcalculation();
Стили программирования
[CamelCase](https://ru.wikipedia.org/wiki/CamelCase)
[snake_case](https://ru.wikipedia.org/wiki/Snake_case)

2024-12-11 13:50 UTC, MarinaPaley commented on Задание 2-1.c
> +    puts("Выберите фигуру для расчета площади:\n0 - Трапеция\n1 - Круг\n");
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

2024-12-15 21:29 UTC, VelichkoIS commented
Исправил документацию, название функции, вместо "магических переменных" сделал сравнение вводимых из stdin символьных значений со значениями enum(так что пользователь может сделать выбор словами).

2024-12-16 13:50 UTC, MarinaPaley approved these changes

2024-12-22 13:13 UTC, merged