Create Задание 2-2.c
VelichkoIS/TKI-142 pull request #13
Opened 2024-10-28 11:32 UTC by VelichkoIS

2024-10-29 17:23 UTC, BalakinaEP requested changes

2024-10-29 17:23 UTC, BalakinaEP commented on Задание 2-2.c
> +double calculateY(double x, double a);
параметры константы

2024-10-29 17:23 UTC, BalakinaEP commented on Задание 2-2.c
> +double input();
void

2024-10-29 17:23 UTC, BalakinaEP commented on Задание 2-2.c
> +int main() {
void

2024-10-29 17:23 UTC, BalakinaEP commented on Задание 2-2.c
> +    if (x != 1) {
Зачем эта проверка?

2024-10-29 17:23 UTC, BalakinaEP commented on Задание 2-2.c
> +    double x;
`double x = 0;`

2024-12-13 13:11 UTC, BalakinaEP requested changes

2024-12-13 13:11 UTC, BalakinaEP commented on Задание 2-2.c
> +double input() {
void

2024-12-13 13:11 UTC, BalakinaEP commented on Задание 2-2.c
> +        return 1;
abort()

2024-12-16 13:48 UTC, MarinaPaley approved these changes

2025-01-15 19:44 UTC, merged