Create Задание3-1.c
VelichkoIS/TKI-142 pull request #17
Opened 2024-11-18 18:39 UTC by VelichkoIS

2024-11-22 13:22 UTC, BalakinaEP requested changes

2024-11-22 13:22 UTC, BalakinaEP commented on Задание3-1.c
> +double input(double*, double*, double*);
Так делать н нужно. Мы последовательно водим по одному элементу

2024-11-22 13:22 UTC, BalakinaEP commented on Задание3-1.c
> +	printf("Введите интервал(два числа через двоеточие):");
нужна проверка ввода. Сделайте как в лекциях

2024-11-25 11:15 UTC, MarinaPaley requested changes

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +* @ breif - принимает значения
не надо пробела

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +	double x, result;
не инициализированы

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +	int c = 1, s = 0;
https://pvs-studio.ru/ru/blog/posts/cpp/1053/

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +		check(x);
`double step = get_step();`

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +	if (c != 1 || (*x) < 0.4 || (*x) > 1) {
Интервал только для тестов

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +	double result = x + pow(x, 1.0 / 2) + pow(x, 1.0 / 3) - 2.5;
1. Одна функция для проверки ОДЗ
2. Вторая функция считает

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +	do {
не надо так

2024-11-25 11:15 UTC, MarinaPaley commented on Задание3-1.c
> +	if (fabs(fmod(x, 0.05)) > 1e-9) {
1. Шаг тоже вводит пользователь
2. Шаг нужно проверить

2024-12-02 12:41 UTC, MarinaPaley requested changes

2024-12-02 12:41 UTC, MarinaPaley commented on Задание3-1.c
> +int check(const float, const float);
Указать явно все параметры

2024-12-02 12:41 UTC, MarinaPaley commented on Задание3-1.c
> +		result = intervalB + pow(intervalB, 1.0 / 2.0) + pow(intervalB, 1.0 / 3.0) - 2.5;
1. `else`
2. `sqrt`, `cbrt`

2024-12-08 08:48 UTC, VelichkoIS commented
Указал параметры при обьявлении, использовал функции взятия корня

2024-12-11 12:49 UTC, MarinaPaley requested changes
![image](https://github.com/user-attachments/assets/8176b209-c1b0-474a-b76d-c28c2ec0cb4a)

2024-12-11 12:49 UTC, MarinaPaley commented on Задание3-1.c
> +float input();
Для документирования кода необходимо использовать [Doxygen](https://www.doxygen.nl/manual/docblocks.html).

2024-12-11 12:49 UTC, MarinaPaley commented on Задание3-1.c
> +	if (fabs(intervalB - intervalE) < FLT_EPSILON) {
1. Я не понимаю глобально, зачем проверять интервал, если потом он будет использоваться в цикле. Если начало будет больше или равно концу, то цикл просто не выполниться. это Не ошибка...
2. Если Вам так нужно проверять (ну хочется), то, почему проверяете только на ==...., почему не проверяете на то, что начало больше конца.

2024-12-15 12:37 UTC, VelichkoIS commented
Исправил документацию, убрал ненужную проверку, исправил количество параметров в функциях корня, поменял тип функции calc на void.

2024-12-16 13:47 UTC, MarinaPaley approved these changes

2024-12-21 22:08 UTC, merged