Create Задание 4-1.c
VelichkoIS/TKI-142 pull request #19
Opened 2024-11-20 18:17 UTC by VelichkoIS

2024-11-25 11:06 UTC, MarinaPaley requested changes

2024-11-25 11:06 UTC, MarinaPaley commented on Задание 4-1.c
> +    printf("0 - случайная генерация чисел\n1 - ручной ввод\nВаш выбор: ");
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

2024-11-25 11:06 UTC, MarinaPaley commented on Задание 4-1.c
> +    scanf_s("%d", value);
нет проверки

2024-11-25 11:06 UTC, MarinaPaley commented on Задание 4-1.c
> +    float* arrayF = (float*)calloc(1, sizeof(int));
либо `float`, или `int`

2024-11-25 11:06 UTC, MarinaPaley commented on Задание 4-1.c
> +    int A, value, stop = 0, c, n, min = -10, max = 20;
[Вредный совет №36 от PVS-Studio. Объявление переменных в начале функции](https://pvs-studio.ru/ru/blog/posts/cpp/1053/)
константы в коде
переменные не инициализированы

2024-11-25 11:06 UTC, MarinaPaley commented on Задание 4-1.c
> +    float* arrayF = (float*)calloc(1, sizeof(int));
нет проверки, что память выделена

2024-11-25 11:06 UTC, MarinaPaley commented on Задание 4-1.c
> +    scanf_s("%d", n);
1. Не проверили, что ввели число
2. Не проверили, что число > 0
3. Не проверили, что память перевыделена

2024-12-09 11:05 UTC, MarinaPaley requested changes

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +* @var s - переменная для хранения количества символов введенных в stdin
параметров нет, а вот `returns `- есть

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +int r_input(int* array, const size_t size);
`void random_input(int* const array, const size_t size);`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +* @param array - содержимое массива
указатель на массив

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +int sum(const size_t size, int* array);
const и const для массива

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +int check_mm(const int min, const int max);
void check_range(const int min, const int max); и @remarks, что заканчивает работу, в случае..

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +enum method {
Документация

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	int* array = (int*)malloc(size * sizeof(int));
не проверили

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	puts("Выберите способ заполнения массива:\n0 - случайными числами\n1 - вручную");
используйте свой `enum`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	sum(size, array);
Не вывели..

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	count(size, array);
не вывели

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	float* array_float = (float*)malloc(size * sizeof(float));
проверка

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +size_t input_p();
`size_t input_positive();`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	return value;
Проверили s, а выводите value

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	int s = scanf_s("%d", &value);
Используйте `input()`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +size_t check_size(const size_t size) {
убрать всю функцию

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	for (int i = 0; i < size; i++) {
`size_t`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	for (int i = 0; i < size; i++) {
`size_t`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	printf("Сумма всех элементов с нечетными индексами: %d\n", temp);
Убрать. Это для `main()`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +size_t division(const size_t size, int* array, float* array_float) {
`void`

2024-12-09 11:05 UTC, MarinaPaley commented on Задание 4-1.c
> +	return 0;
убрать

2024-12-15 21:11 UTC, VelichkoIS commented
Исправил документацию, типы возвращаемых данных, добавил проверку выделения памяти, вынес функции выведения в main, убрал ненужную функцию, заменил "магические константы в коде" на сравнение вводимых символьных значений с enum(так что пользователь может выбрать словами как заполнять массив).

2024-12-16 13:41 UTC, MarinaPaley requested changes

2024-12-16 13:41 UTC, MarinaPaley commented on Задание 4-1.c
> +void comparison(char* temp, enum method* choice, int* array) {
не надо так, просто `enum `к `int`

2024-12-16 14:24 UTC, MarinaPaley requested changes

2024-12-16 14:24 UTC, MarinaPaley commented on Задание 4-1.c
> +	return (size_t)s;
а где проверка на то, что оно положительное?

2024-12-16 14:41 UTC, MarinaPaley approved these changes

2024-12-22 11:55 UTC, merged