Feature/3 2
VelichkoIS/TKI-142 pull request #23
Opened 2024-12-08 09:18 UTC by VelichkoIS

2024-12-09 11:21 UTC, MarinaPaley requested changes

2024-12-09 11:21 UTC, MarinaPaley commented on Задание3-2.c
> +int check(const int n);
`int get_positive();`

2024-12-09 11:21 UTC, MarinaPaley commented on Задание3-2.c
> +	int e = check(input());
`epsilon` - число с плавающей точкой

2024-12-15 12:57 UTC, VelichkoIS commented on Задание3-2.c
> +	int e = check(input());
![image](https://github.com/user-attachments/assets/fb75956e-3e51-4db7-a7a7-15a98a559d72)
Здравствуйте, в итоге делать как в задании или просто с эпсилоном ?(пока оставил как есть)

2024-12-15 12:59 UTC, VelichkoIS commented
Исправил документацию, обьеденил функции input() и check() в get_positive(),

2024-12-16 13:30 UTC, MarinaPaley approved these changes

2024-12-22 15:53 UTC, merged