Feature/1 2
VelichkoIS/TKI-142 pull request #26
Opened 2024-12-08 21:21 UTC by VelichkoIS

2024-12-13 13:12 UTC, BalakinaEP requested changes

2024-12-13 13:12 UTC, BalakinaEP commented on Задание1-2.c
> +	const float p = 3.14;
Это константа M_PI

2024-12-13 13:12 UTC, BalakinaEP commented on Задание1-2.c
> +float input();
void

2024-12-13 13:12 UTC, BalakinaEP commented on Задание1-2.c
> +int main() {
void

2024-12-13 13:12 UTC, BalakinaEP commented on Задание1-2.c
> +float input() {
void

2024-12-16 13:31 UTC, MarinaPaley requested changes

2024-12-16 13:31 UTC, MarinaPaley commented on Задание1-2.c
> +	double V = 4 / 3 * M_PI * pow(R, 3);
`4 / 3 == 0`

2024-12-23 11:11 UTC, Vadimololo19 approved these changes

2025-01-15 19:47 UTC, merged