Feature/3 3
VelichkoIS/TKI-142 pull request #27
Opened 2024-12-08 21:24 UTC by VelichkoIS

2024-12-09 11:15 UTC, MarinaPaley requested changes

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +int check(const float intervalB, const float intervalE);
`void`

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +float check_step(const float step);
Здесь вводить и проверять и отдавать шаг

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +	if (step < FLT_EPSILON) {
`float step = input();`
и дальше как у Вас

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +float check_step(const float step);
`float get_step();`

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +	const float step = check_step(input());
`const float step = get_step();`

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +	  return pow(exp(1), x);
`return exp(x);`

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +	float a = recurent(x, 0);
`float current = recurent(x, 0); `

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +	while (fabs(a) >= epsilon) {
`while (fabs(a) >= epsilon - DBL_EPSILON) `

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +		a = recurent(x, k);
`current *= recurrent(x, k);`

2024-12-09 11:15 UTC, MarinaPaley commented on Задание 3-3.c
> +	return (4 * k + 1) * pow(x, 4) / (4 * k + 5);
неправильно посчитали `return x / k;`

2024-12-15 13:55 UTC, VelichkoIS commented
Исправил документацию, убрал ненужную проверку интервала, исправил запись экспоненты, сделал конструкцию double step = get_step(), изменил рекурентный расчет следующего члена последовательности.

2024-12-16 13:45 UTC, MarinaPaley approved these changes

2024-12-16 13:45 UTC, MarinaPaley commented on Задание 3-3.c
> +	int s = scanf_s("%lf", &value);
```c
double value =  input();
if value ...
```

2025-01-15 19:57 UTC, merged