Feature/4 2
VelichkoIS/TKI-142 pull request #28
Opened 2024-12-09 11:23 UTC by VelichkoIS

2024-12-09 12:12 UTC, MarinaPaley requested changes
Как и в 4-1

2024-12-09 12:12 UTC, MarinaPaley commented on Задание 4-2.c
> +size_t check_size(const size_t size);
Это неправильно( на вход приходит беззнаковое

2024-12-23 11:15 UTC, Vadimololo19 requested changes

2024-12-23 11:15 UTC, Vadimololo19 commented on Задание4-2/main.c
> +	create_array(array, new_array, size);
Переименовать под 3-е задание

2024-12-23 11:15 UTC, Vadimololo19 commented on Задание4-2/main.c
> +	int* new_array = (int*)malloc(size * sizeof(int)); ;
функцию для создания массива

2024-12-23 12:19 UTC, Vadimololo19 approved these changes

2025-01-15 19:54 UTC, merged